/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import Clases.Datos;
import Clases.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JULIANESCOBAR
 */
public class frmUsuario extends javax.swing.JInternalFrame {

    private Datos misDatos;
    private int usuAct = 0;
    private boolean nuevo = false;
    private DefaultTableModel miTabla;

    public void setDatos(Datos misDatos) {
        this.misDatos = misDatos;

    }

    public frmUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblDocumento = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblPregunta = new javax.swing.JLabel();
        lblRespuesta = new javax.swing.JLabel();
        txtRespuesta = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        lblConfirmar = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cmbPregunta = new javax.swing.JComboBox();
        txtContraseña = new javax.swing.JPasswordField();
        lblPerfil = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtConfirmar = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTabla = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Usuarios");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        lblDocumento.setText("Documento*:");

        txtDocumento.setEnabled(false);
        txtDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuario*:");

        txtUsuario.setEnabled(false);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        lblCorreo.setText("Correo*:");

        txtCorreo.setEnabled(false);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        lblPregunta.setText("Pregunta Secreta*:");

        lblRespuesta.setText("Respuesta*:");

        txtRespuesta.setEnabled(false);
        txtRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuestaActionPerformed(evt);
            }
        });

        lblContraseña.setText("Contraseña*:");

        lblConfirmar.setText("Confirmar*:");

        btnCrear.setText("Nuevo");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cmbPregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciones una pregunta...", "Lugar de nacimiento de la madre?", "Nombre abuela/o?", "Color favorito?", "Canciòn favorita?", " ", " " }));
        cmbPregunta.setEnabled(false);

        txtContraseña.setEnabled(false);

        lblPerfil.setText("Perfil*:");

        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione un perfil ...", "Administrador del sistema", "Administrador del Bufete", "Abogado titular", "Abogado", "Empleado", "Cliente", " " }));
        cmbPerfil.setEnabled(false);
        cmbPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPerfilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("* Campos obligatorios");

        txtConfirmar.setEnabled(false);

        tblTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblTabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblCorreo)
                                    .addComponent(lblPregunta)
                                    .addComponent(lblRespuesta)
                                    .addComponent(lblContraseña)
                                    .addComponent(lblConfirmar)
                                    .addComponent(lblDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRespuesta)
                                    .addComponent(txtContraseña)
                                    .addComponent(txtConfirmar)
                                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDocumento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPerfil)
                                .addGap(12, 12, 12)
                                .addComponent(cmbPerfil, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDocumento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCorreo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPerfil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuestaActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        //Habilita botones 
        btnConsultar.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);

        //Habilita campos
        txtConfirmar.setEnabled(true);
        txtContraseña.setEnabled(true);
        txtCorreo.setEnabled(true);
        txtDocumento.setEnabled(true);
        txtRespuesta.setEnabled(true);
        txtUsuario.setEnabled(true);
        cmbPregunta.setEnabled(true);
       
        cmbPerfil.setEnabled(true);

        //Limpiar campos
        txtUsuario.setText("");
        txtConfirmar.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtDocumento.setText("");
        cmbPregunta.setSelectedItem(0);
        txtRespuesta.setText("");        
        cmbPerfil.setSelectedItem(0);

        //Activamos el flag de registro nuevo
        nuevo = true;

        //foco al campo documento
        txtDocumento.requestFocusInWindow();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String documento = JOptionPane.showInputDialog("Ingrese còdigo de usuario");
        if (documento.equals("")) {
            return;
        }
        int pos = misDatos.posicionUsuario(documento);
        if (pos == -1) {
            JOptionPane.showMessageDialog(rootPane, "Usuario no existe");
            return;
        }
        usuAct = pos;
        mostrarRegistro();

        btnCrear.setEnabled(false);
        btnBorrar.setEnabled(true);
        btnModificar.setEnabled(true);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(true);

        //Deshabilita campos
        txtConfirmar.setEnabled(false);
        txtContraseña.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtDocumento.setEnabled(false);
        txtRespuesta.setEnabled(false);
        txtUsuario.setEnabled(false);
        cmbPregunta.setEnabled(false);
        cmbPerfil.setEnabled(false);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        btnConsultar.setEnabled(false);
        btnCrear.setEnabled(false);
        btnBorrar.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnCancelar.setEnabled(true);

        //Habilita campos
        txtConfirmar.setEnabled(true);
        txtContraseña.setEnabled(true);
        txtCorreo.setEnabled(true);
        txtDocumento.setEnabled(false);
        txtRespuesta.setEnabled(true);
        txtUsuario.setEnabled(true);
        cmbPregunta.setEnabled(true);
        cmbPerfil.setEnabled(true);

        //Activamos el flag de registro nuevo
        nuevo = false;

        //foco al campo documento
        txtUsuario.requestFocusInWindow();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        //Validaciones
        if (txtDocumento.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un documento");
            txtDocumento.requestFocusInWindow();
            return;
        }
        if (txtUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un usuario");
            txtUsuario.requestFocusInWindow();
            return;
        }
        if (txtCorreo.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un Correo");
            txtCorreo.requestFocusInWindow();
            return;
        }
        if (cmbPregunta.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un pregunta");
            cmbPregunta.requestFocusInWindow();
            return;
        }

        if (txtRespuesta.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un respuesta");
            txtRespuesta.requestFocusInWindow();
            return;
        }

        String contraseña = new String(txtContraseña.getPassword());
        String confirmacion = new String(txtConfirmar.getPassword());

        if (contraseña.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una contraseña");
            txtContraseña.requestFocusInWindow();
            return;
        }

        if (confirmacion.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar una confirmaciòn");
            txtConfirmar.requestFocusInWindow();
            return;
        }

        if (!contraseña.equals(confirmacion)) {
            JOptionPane.showMessageDialog(rootPane, "La contraseña y la confirmaciòn no coinciden");
            txtConfirmar.requestFocusInWindow();
            return;
        }

      

        if (cmbPerfil.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar un perfil");
            cmbPerfil.requestFocusInWindow();
            return;
        }

        int pos = misDatos.posicionUsuario(txtDocumento.getText());
        if (nuevo) {
            if (pos != -1) {
                JOptionPane.showMessageDialog(rootPane, "Usuario ya existe");
                txtDocumento.requestFocusInWindow();
                return;
            }

        } else {
            if (pos == -1) {
                JOptionPane.showMessageDialog(rootPane, "Usuario no existe");
                txtDocumento.requestFocusInWindow();
                return;
            }

        }
              
                                       
        Usuario miUsuario;
        miUsuario = new Usuario(txtDocumento.getText(), txtUsuario.getText(),
                txtCorreo.getText(),cmbPregunta.getSelectedIndex(),
                txtRespuesta.getText(), contraseña, cmbPerfil.getSelectedIndex());
        String msg;
        if (nuevo) {
            msg = misDatos.agregarUsuario(miUsuario);
        } else {
            msg = misDatos.modificarUsuario(miUsuario, pos);
        }

        JOptionPane.showMessageDialog(rootPane, msg);

        btnCrear.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnBorrar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        //Limpiar campos
        txtConfirmar.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtDocumento.setText("");
        txtRespuesta.setText("");
        txtUsuario.setText("");
        cmbPregunta.setSelectedItem(0);
        
        cmbPerfil.setSelectedItem(0);

        //Deshabilita campos
        txtConfirmar.setEnabled(false);
        txtContraseña.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtDocumento.setEnabled(false);
        txtRespuesta.setEnabled(false);
        txtUsuario.setEnabled(false);
        cmbPregunta.setEnabled(false);
        
        cmbPerfil.setEnabled(false);
         llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

   
    
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
      
        int rta = JOptionPane.showConfirmDialog(rootPane, "Esta seguro de borrar el registro");
        if (rta != 0) {
            return;
        }
        String msg;
        msg = misDatos.borrarUsuario(usuAct);
        JOptionPane.showMessageDialog(rootPane, msg);
        usuAct = 0;
        mostrarRegistro();
        
        
        btnCrear.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnBorrar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        //Limpiar campos
        txtConfirmar.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtDocumento.setText("");
        txtRespuesta.setText("");
        txtUsuario.setText("");
        cmbPregunta.setSelectedItem(0);
       
        cmbPerfil.setSelectedItem(0);

        //Deshabilita campos
        txtConfirmar.setEnabled(false);
        txtContraseña.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtDocumento.setEnabled(false);
        txtRespuesta.setEnabled(false);
        txtUsuario.setEnabled(false);
        cmbPregunta.setEnabled(false);
        cmbPerfil.setEnabled(false);
        
        
         llenarTabla();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        btnCrear.setEnabled(true);
        btnConsultar.setEnabled(true);
        btnBorrar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnGuardar.setEnabled(false);
        btnCancelar.setEnabled(false);

        //Limpiar campos
        txtConfirmar.setText("");
        txtContraseña.setText("");
        txtCorreo.setText("");
        txtDocumento.setText("");
        txtRespuesta.setText("");
        txtUsuario.setText("");
        cmbPregunta.setSelectedItem(0);
        cmbPerfil.setSelectedItem(0);

        //Deshabilita campos
        txtConfirmar.setEnabled(false);
        txtContraseña.setEnabled(false);
        txtCorreo.setEnabled(false);
        txtDocumento.setEnabled(false);
        txtRespuesta.setEnabled(false);
        txtUsuario.setEnabled(false);
        cmbPregunta.setEnabled(false);
        cmbPerfil.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
//        txtDocumento.setText("" + misDatos.getUsuario()[usuAct].getDocumento());
//        txtUsuario.setText(misDatos.getUsuario()[usuAct].getUsuario());
//        txtCorreo.setText(misDatos.getUsuario()[usuAct].getCorreo());
//        cmbPregunta.setSelectedIndex(misDatos.getUsuario()[usuAct].getPregunta());
//        txtRespuesta.setText(misDatos.getUsuario()[usuAct].getRespuesta());
//        txtContraseña.setText(misDatos.getUsuario()[usuAct].getContraseña());
//        txtConfirmar.setText(misDatos.getUsuario()[usuAct].getContraseña());
//         cmbPerfil.setSelectedIndex(misDatos.getUsuario()[usuAct].getPerfil());
//
//        
//        llenarTabla();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmbPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPerfilActionPerformed

    private void mostrarRegistro() {
        txtDocumento.setText("" + misDatos.getUsuario()[usuAct].getDocumento());
        txtUsuario.setText(misDatos.getUsuario()[usuAct].getUsuario());
        txtCorreo.setText(misDatos.getUsuario()[usuAct].getCorreo());
        cmbPregunta.setSelectedIndex(misDatos.getUsuario()[usuAct].getPregunta());
        txtRespuesta.setText(misDatos.getUsuario()[usuAct].getRespuesta());
        txtContraseña.setText(misDatos.getUsuario()[usuAct].getContraseña());
        txtConfirmar.setText(misDatos.getUsuario()[usuAct].getContraseña());
        cmbPerfil.setSelectedIndex(misDatos.getUsuario()[usuAct].getPerfil());

    }
    
    private void llenarTabla(){
        String titulos [] = {"Documento","Usuario","Correo","Estado","Perfil"};
        String registro [] = new String [5];
        miTabla = new DefaultTableModel(null, titulos);
        for (int i = 0; i < misDatos.numeroUsuarios();i++){
            registro [0] ="" + misDatos.getUsuario()[i].getDocumento();
            registro [1] = misDatos.getUsuario()[i].getUsuario();
            registro [2] = misDatos.getUsuario()[i].getCorreo();
            registro [4] = perfil (misDatos.getUsuario()[i].getPerfil());
            miTabla.addRow(registro);
        }
       tblTabla.setModel (miTabla);
    }

    private String perfil (int perfil){
        switch (perfil){
            case 1:  return "Administrador del sistema";
            case 2:  return "Administrador del bufete";
            case 3:  return "Abogado titular";
            case 4:  return "Abogado";
            case 5:  return "Empleado";
            case 6:  return "Cliente";    
        }
        return null;
    }
    
    private String estado (int estado){
        if (estado == 1){
            return "Activo";
        }else{
           return "Inactivo"; 
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmbPerfil;
    private javax.swing.JComboBox cmbPregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblConfirmar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDocumento;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblTabla;
    private javax.swing.JPasswordField txtConfirmar;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
